// GENERATED by tools/gen_constraints_header.py from problem.json — do not edit.
// Regenerate with:  python3 tools/gen_constraints_header.py <problem-dir>
#pragma once


// ---- global bounds -------------------------------------------------------
// value: 1 \le a, b \le 1000
static const long long VALUE_MIN = 1;
static const long long VALUE_MAX = 1000;

// ---- subtask g1 (100%) ----------------------------------------
//   Không có ràng buộc gì thêm
static const long long G1_VALUE_MIN = 1;
static const long long G1_VALUE_MAX = 1000;
