#!/usr/bin/env python3
"""Generate files/constraints.h from problem.json.

The validator cannot take bounds on the command line — testlib opts are
generator-only (plan.md O-09) — so bounds must be compile-time constants.
Generating them from problem.json is what makes drift impossible rather than
merely discouraged.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from tools.problem_meta import Problem, load

HEADER = """\
// GENERATED by tools/gen_constraints_header.py from problem.json — do not edit.
// Regenerate with:  python3 tools/gen_constraints_header.py <problem-dir>
#pragma once
"""


def identifier(raw: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", raw).strip("_").upper()


def _emit(name: str, value: int) -> str:
    return f"static const long long {name} = {value};"


def render(problem: Problem) -> str:
    lines = [HEADER, ""]

    lines.append("// ---- global bounds " + "-" * 55)
    for c in problem.constraints:
        if c.min is None and c.max is None:
            continue
        lines.append(f"// {c.id}: {c.expr}")
        if c.min is not None:
            lines.append(_emit(f"{identifier(c.id)}_MIN", c.min))
        if c.max is not None:
            lines.append(_emit(f"{identifier(c.id)}_MAX", c.max))
        lines.append("")

    for sub in problem.subtasks:
        lines.append(f"// ---- subtask {sub.id} ({sub.points}%) " + "-" * 40)
        for text in sub.constraints_text:
            lines.append(f"//   {text}")
        for c in problem.constraints:
            if c.min is None and c.max is None:
                continue
            bound = problem.effective_bound(sub.id, c.id)
            prefix = f"{identifier(sub.id)}_{identifier(c.id)}"
            if bound.min is not None:
                lines.append(_emit(f"{prefix}_MIN", bound.min))
            if bound.max is not None:
                lines.append(_emit(f"{prefix}_MAX", bound.max))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: gen_constraints_header.py <problem-dir>", file=sys.stderr)
        return 2
    problem_dir = Path(argv[1])
    problem = load(problem_dir / "problem.json")
    out = problem_dir / "files" / "constraints.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(problem), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
