#!/usr/bin/env python3
"""Generate files/constraints.h from problem.json.

The validator cannot take bounds on the command line — testlib opts are
generator-only (plan.md O-09) — so bounds must be compile-time constants.
Generating them from problem.json is what makes drift impossible rather than
merely discouraged.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from tools.problem_meta import Problem, ProblemMetaError, load

HEADER = """\
// GENERATED by tools/gen_constraints_header.py from problem.json — do not edit.
// Regenerate with:  python3 tools/gen_constraints_header.py <problem-dir>
#pragma once
"""


def identifier(raw: str) -> str:
    """Convert a constraint or subtask ID to a legal C++ identifier.

    Replaces non-alphanumeric characters with underscores, strips leading/trailing
    underscores, and converts to uppercase. If the result starts with a digit,
    prefixes it with 'C_' to ensure it is a legal identifier.
    """
    normalized = re.sub(r"[^0-9a-zA-Z]+", "_", raw).strip("_").upper()
    if normalized and normalized[0].isdigit():
        normalized = "C_" + normalized
    return normalized


def _emit(name: str, value: int) -> str:
    return f"static const long long {name} = {value};"


def _has_bounds(bound) -> bool:
    """Check if a Bound has any constraint (min or max)."""
    return bound.min is not None or bound.max is not None


def render(problem: Problem) -> str:
    lines = [HEADER, ""]

    # Track emitted identifiers to detect collisions
    # Maps emitted_name -> source_id (e.g., "LEN_A_MIN" -> "len_a")
    emitted: dict[str, str] = {}

    def _check_and_track(emitted_name: str, source_id: str) -> None:
        """Check for identifier collisions and track the emission."""
        if emitted_name in emitted:
            other_id = emitted[emitted_name]
            if other_id != source_id:
                raise ProblemMetaError(
                    f"Identifier collision: constraint/subtask IDs {source_id!r} and {other_id!r} "
                    f"both map to C++ identifier {emitted_name!r}"
                )
        emitted[emitted_name] = source_id

    lines.append("// ---- global bounds " + "-" * 55)
    for c in problem.constraints:
        if not _has_bounds(c):
            continue
        lines.append(f"// {c.id}: {c.expr}")
        if c.min is not None:
            min_name = f"{identifier(c.id)}_MIN"
            _check_and_track(min_name, c.id)
            lines.append(_emit(min_name, c.min))
        if c.max is not None:
            max_name = f"{identifier(c.id)}_MAX"
            _check_and_track(max_name, c.id)
            lines.append(_emit(max_name, c.max))
        lines.append("")

    for sub in problem.subtasks:
        lines.append(f"// ---- subtask {sub.id} ({sub.points}%) " + "-" * 40)
        for text in sub.constraints_text:
            lines.append(f"//   {text}")
        for c in problem.constraints:
            bound = problem.effective_bound(sub.id, c.id)
            if not _has_bounds(bound):
                continue
            prefix = f"{identifier(sub.id)}_{identifier(c.id)}"
            if bound.min is not None:
                min_name = f"{prefix}_MIN"
                _check_and_track(min_name, f"{sub.id}.{c.id}")
                lines.append(_emit(min_name, bound.min))
            if bound.max is not None:
                max_name = f"{prefix}_MAX"
                _check_and_track(max_name, f"{sub.id}.{c.id}")
                lines.append(_emit(max_name, bound.max))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: gen_constraints_header.py <problem-dir>", file=sys.stderr)
        return 2
    problem_dir = Path(argv[1])
    problem = load(problem_dir / "problem.json")
    out = problem_dir / "files" / "constraints.h"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(problem), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
